---
- name: verify files to package manager checksums (grep)  # noqa command-instead-of-shell
  shell: "{{ item }}"
  args:
    executable: /bin/sh
    chdir: "{{ temp_dir }}"
  register: res
  failed_when: res.rc == 0
  changed_when: false
  ignore_errors: true
  loop:
    # Finding binaries that don’t belong to any package
    - 'find /proc/*/exe -exec readlink {} + | xargs dpkg -S | grep "no path" 1>find_bin'

- name: verify files to package manager checksums (retval)  # noqa command-instead-of-shell
  shell: "{{ item }}"
  args:
    executable: /bin/sh
    chdir: "{{ temp_dir }}"
  register: res
  changed_when: false
  ignore_errors: true
  loop:
    # Verifying the binaries running match what was in the packages
    - 'find /proc/*/exe -exec readlink {} + | xargs dpkg -S | cut -d: -f1 | xargs dpkg -V 1>verify_bin'
    # Verify all
    - 'dpkg -V 1>verify_all'
    # Verify PAM modules
    - 'find /lib/x86_64-linux-gnu/security | xargs dpkg -S | cut -d: -f1 | uniq | xargs dpkg -V 1>verify_pam'
