---
- name: verify files to package manager checksums (retval)  # noqa command-instead-of-shell
  shell: "{{ item }}"
  args:
    executable: /bin/sh
    chdir: "{{ temp_dir }}"
  register: res
  changed_when: false
  ignore_errors: true
  loop:
    # check base system
    - 'freebsd-update IDS 1>checksums_freebds'
    # check packages
    - 'pkg check -s -a 1>checksums_pkg'
