---
- name: create service user
  user:
    name: tcphoneypot

- name: app
  copy:
    src: files/tcp-honeypot.py
    dest: /home/tcphoneypot/tcp-honeypot.py
    owner: root
    group: root
    mode: 0644

- name: service unit
  copy:
    src: files/tcphoneypot.service
    dest: /etc/systemd/system/tcphoneypot.service
    owner: root
    group: root
    mode: 0644

- name: ensure service
  systemd:
    name: tcphoneypot
    enabled: true
    state: started
